### ISSUE TITLE
在 Windows 平台下应用会不定时闪退

### ISSUE THREAD

**Issue by WinExp** [BeyondDimension/NotifyIcon#2]
我使用的是 WinUI 3 UI 库来制作的应用程序。在我生成并运行后，应用程序正常运行。但是在过了几秒之后，应用程序闪退，没有捕获到异常，应用程序的输出也没有提示任何异常。我已经尝试在各大搜索平台上寻找 WinUI 3 下的托盘库，但是不是报错就是闪退。
![image](https://user-images.githubusercontent.com/55543397/160076664-2139c83d-e343-4cec-bd28-663f1d14f1a9.png)

**Comment by AigioL** [comment]
今天才看到这个 issue...
WinUI 3 也许调用 WinForms 的托盘 API 比较合适，但是 WinForms 的程序集占用空间也不小
建了一个 WinUI 3 的示例项目，测试了是正常的没有闪退

但 WinUI 3/MAUI 的 Application 没有 Exit 事件，有没有类似的替代品？
因为要在程序退出时释放托盘，才能在任务栏上消失

在 Samples.WinUI3App1 这个示例项目通过使用自定义 Program 类，即 [WinUIProgram](https://github.com/BeyondDimension/NotifyIcon/blob/main/Samples.WinUI3App1/WinUIProgram.cs) 实现了 Exit 事件

**Comment by WinExp** [comment]
hmmm
我再试试吧，谢谢大佬开发的库

**Comment by WinExp** [comment]
还有就是大佬的托盘有没有右键菜单啊，之前用的库特别麻烦

**Comment by AigioL** [comment]
https://github.com/BeyondDimension/NotifyIcon/blob/main/Samples.ClassLibrary1/NotifyIconHelper.cs#L58-L66
这段代码是添加右键菜单项的，目前只有一级菜单的支持，分割线之类的也不支持，由于 Win32 的菜单样式太丑了，通常需要自定义样式等高级功能，都是通过自己建一个窗口，在右键事件上根据光标位置显示自己的窗口

**Comment by WinExp** [comment]
好的

**Comment by WinExp** [comment]
话说大佬知道winui3到底怎么自定义标题栏啊，我按照官方的方法没办法用三大金刚按钮（可以不回答）

**Comment by AigioL** [comment]
WinUI3 不太清楚，可能和 UWP 类似吧，不过 TitleBar 自定义通常都是将窗口改成无边框窗口，自己绘制四周一圈的内容，包括顶部的 TitleBar，与左右下的边框，WPF 中就经常使用这种方案

你可以看看 UWP 相关的方案 https://edi.wang/post/2015/10/8/windows-10-uwp-title-bar

**Comment by WinExp** [comment]
好的，谢谢大佬，我close了
