### ISSUE TITLE
希望能增加子级菜单和菜单分割线

### ISSUE THREAD

**Issue by Gaoyifei1011** [BeyondDimension/NotifyIcon#3]
希望能增加子级菜单和菜单分割线
通过winui3的使用用例，目前仅能简单的创建菜单，但目前没有看见添加多级菜单和分割线的用例，未来能否完善一下呢？
同时希望未来创建菜单时可以直接通过xaml前端快速创建，绑定使用命令

**Comment by AigioL** [comment]
Win32原生的右键菜单样式不怎么好看，加分割线多级菜单的需求可以参考 https://github.com/BeyondDimension/SteamTools/blob/2.8.6/src/ST.Client.Desktop.Avalonia/Application/UI/NotifyIconHelper.cs#L68 
上在右键点击事件时显示一个窗口，通过自定义窗口来展示菜单，win32api部分没有计划完善

**Comment by Gaoyifei1011** [comment]
好的，非常感谢。我已经在我的程序里实现了自己的托盘图标右键菜单了，感谢您提供的案例。
